set nocompatible

set directory=~/dotfiles/vim/tmp
set backupdir=~/dotfiles/vim/backup

set mouse=a

syntax on

set shiftwidth=3 autoindent tabstop=3 smarttab number mouse=a bg=dark
set hlsearch
set hidden
set number

set wildmenu
set wildignore=.git,*.app,*.pbxindex
set wildmode=list:longest

set ruler
set hlsearch
set incsearch

set wrap
set visualbell
set title


set tabstop=2
set shiftwidth=2
set expandtab

set laststatus=2
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P


