HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.zsh_history

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt NO_BEEP
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt NO_SHARE_HISTORY

